### ISSUE TITLE
USB socket

### ISSUE THREAD

**Issue by bench2012** [GadgetReboot/ESP32-A1S#3]
Hi,

First of thanks for a very interesting board. I was going the same way, when I came across your project on GitHub. I managed to make a few board, but since there is no BOM list, just wonder which and where you got the usb socket? Usb socket could be a real pain to get right.

Many thx.

Bench

**Comment by GadgetReboot** [comment]
The USB Micro-B connector on the board is GCT p/n USB3076-30-A   available from Digikey, Mouser etc

**Comment by bench2012** [comment]
> The USB Micro-B connector on the board is GCT p/n USB3076-30-A available from Digikey, Mouser etc

Many thx. Will let you know how I get with this project. Again thanks for designing the board.
